# 변수명 임의 변경 금지

company_en: EXIT Co.
company_kr: 주식회사 엑시트
ceo: 이승준
duty: 이승준
bs_number: 701-86-03521
address: '충청남도 천안시 서북구 천안천4길 32 그린스타트업타운 (우: 31145)'
tel_number: 010-8384-6126
fax_number: 0504-482-6126
email: exitinfo08@gmail.com
kakao: 'https://open.kakao.com/o/sl7JVmqh'

description: 주식회사 엑시트(EXIT)는 시스템/ 제품/ 경영 인증컨설팅을 제공하는 인증 심사 및 컨설팅 기업입니다.
sub_description: 합리적인 인증 심사 & 컨설팅 기업